[env]
PATH = { value = "D:\\Intellicrack\\.pixi\\envs\\default\\bin;D:\\Intellicrack\\.pixi\\envs\\default\\Library\\mingw-w64\\bin", relative = true }

[build]
rustflags = [
    "-L", "D:\\Intellicrack\\.pixi\\envs\\default\\libs",
]
