[env]
PYO3_PYTHON = "D:\\Intellicrack\\.pixi\\envs\\default\\python.exe"
PYTHONHOME = "D:\\Intellicrack\\.pixi\\envs\\default"
PYTHON_SYS_EXECUTABLE = "D:\\Intellicrack\\.pixi\\envs\\default\\python.exe"
PATH = { value = "D:\\Intellicrack\\.pixi\\envs\\default\\bin;D:\\Intellicrack\\.pixi\\envs\\default\\Library\\mingw-w64\\bin", relative = true }

[build]
rustflags = [
  "-L",
  "D:\\Intellicrack\\.pixi\\envs\\default\\libs" 
]
